[package]
name = "sui_nft_bootcamp"
version = "1.0.0"

[addresses]
sui_nft_bootcamp = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[dev-dependencies]




